export const GET_USER = "GET_USER"
export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const RESTORE_USER = "RESTORE_USER"
export const GOOGLE_LOGIN = "GOOGLE_LOGIN"

export const UPDATE_PLAN = "UPDATE_PLAN"
export const DELETE_PLAN = "DELETE_PLAN"

export const GET_REVIEW = "GET_REVIEW"
export const CREATE_REVIEW = "CREATE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"

export const GET_TRANSACTION = "GET_TRANSACTION"
export const CREATE_TRANSACTION = "CREATE_TRANSACTION"
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"

export const GET_SERVICES = "GET_SERVICES"
export const CREATE_SERVICES = "CREATE_SERVICES"
export const DELETE_SERVICES = "DELETE_SERVICES"