export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const RESTORE_USER = "RESTORE_USER";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";

export const SEARCH_SERVICES = "SEARCH_SERVICES";
export const FILTERS_SERVICES = "FILTERS_SERVICES";
export const CREATE_SERVICES = "CREATE_SERVICES";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_SERVICES = "DELETE_SERVICES";

export const GET_REVIEW = "GET_REVIEW";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";


export const SET_POPUP = "SET_POPUP"
export const CLEAR_POPUP = "CLEAR_POPUP"

export const GET_POSTIG = "GET_POSTIG";
export const CREATE_POSTIG = "CREATE_POSTIG";
export const UPDATE_POSTIG = "UPDATE_POSTIG";
export const DELETE_POSTIG = "DELETE_POSTIG";

